### ISSUE TITLE
batch doesn't run correctly on windows system

### ISSUE THREAD

**Issue by YingxiaoKong** [ProfHoekstra/bluesky#147]
Hi,

I have tried to use batch with a Mac system and it runs quite well. To speed up the simulation, I tried it on windows system. 
there are 2 scn files, one is traffic4 which contains the wind direction that is unknown:
#####traffic4.scn is used to simulate different wind direction
00:00:00.00>SNAPLOG ON,1
00:00:00.00>CRE REP1,B744,50,10,90,FL250,300
00:00:00.00>noise on
00:00:00.00>PAN REP1
00:00:00.00>FF
00:00:00.00> WIND 50,10,*,%0,150
#00:00:00.00>REP1 VNAV ON
#00:00:00.00>REP1 LNAV ON
00:00:00.00>ORIG REP1, 50,10
00:00:00.00>DEST REP1, 50,20

Another one is a batch4_4.scn file which provides the traffic4.scn with a wind direction:
00:00:00.00>SCEN test401
00:00:00.00>PCALL traffic4.scn 201.8014
00:00:00.00>FF
00:56:00.00>HOLD
00:56:00.00>RESET

The problem is that, when I tried to run this on windows system, it could not recognize the given argument ,the wind direction,in the batch file. It always gives me an warning like: too few arguments. 
I have tried it on 3 windows computer and they all have this problem. Could you tell me why and how to solve it? Thanks!

**Comment by ProfHoekstra** [comment]
Dr. Joost Ellerbroek has a Mac, I use Windows. Originally both the PCALL and WIND command arguments were developed on my Windows system so they worked then. So I’ll have a look at the example your giving on my Windows PC to see what’s happening.

Best regards,
    Jacco Hoekstra


On 21 Mar 2018, at 22:13, YingxiaoKong <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I have tried to use batch with a Mac system and it runs quite well. To speed up the simulation, I tried it on windows system.
there are 2 scn files, one is traffic4 which contains the wind direction that is unknown:
#####traffic4.scn is used to simulate different wind direction
00:00:00.00>SNAPLOG ON,1
00:00:00.00>CRE REP1,B744,50,10,90,FL250,300
00:00:00.00>noise on
00:00:00.00>PAN REP1
00:00:00.00>FF
00:00:00.00> WIND 50,10,*,%0,150
#00:00:00.00>REP1 VNAV ON
#00:00:00.00>REP1 LNAV ON
00:00:00.00>ORIG REP1, 50,10
00:00:00.00>DEST REP1, 50,20

Another one is a batch4_4.scn file which provides the traffic4.scn with a wind direction:
00:00:00.00>SCEN test401
00:00:00.00>PCALL traffic4.scn 201.8014
00:00:00.00>FF
00:56:00.00>HOLD
00:56:00.00>RESET

The problem is that, when I tried to run this on windows system, it could not recognize the given argument ,the wind direction,in the batch file. It always gives me an warning like: too few arguments.
I have tried it on 3 windows computer and they all have this problem. Could you tell me why and how to solve it? Thanks!

**Comment by ProfHoekstra** [comment]
And I've tried yur example on my windows systems and it all works perfectly: Getwind gives me the wind as defined. I've ran it both in batch and called it from the console. All of these work without problems.

P.S. I'm using Python 3.6.3, what version are you using? (Even though I think any >=3.5 would do)

**Comment by YingxiaoKong** [comment]
Hi Joost,

On one windows system I just installed the release version of bluesky directly, no python was installed before. On another windows system I installed  anaconda and some other packages that are needed. Both of them doesn’t run correctly when using batch to give them some argument…..



On Mar 22, 2018, at 1:35 AM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com>> wrote:


And I've tried yur example on my windows systems and it all works perfectly: Getwind gives me the wind as defined. I've ran it both in batch and called it from the console. All of these work without problems.

P.S. I'm using Python 3.6.3, what version are you using? (Even though I think any >=3.5 would do)

**Comment by ProfHoekstra** [comment]
You're not running the latest version. Instead of installing a release, simply click the green button "Download as zip" and you have the latest version.

Then install Python 3.6 without any bundle. Then right click ad "Run as Administrator" the batch file named:
                   install-required-modules-windows-run-as-administrator.bat

 to install the required packages.

See also the wiki: [https://github.com/ProfHoekstra/bluesky/wiki/Installation](https://github.com/ProfHoekstra/bluesky/wiki/Installation)

Best regards,
      Jacco Hoekstra

**Comment by YingxiaoKong** [comment]
Thanks Joost! I will try now!

On Mar 22, 2018, at 9:33 AM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com>> wrote:


You're not running the latest version. Instead of installing a release, simply click the green button "Download as zip" and you have the latest version.

Then install Python 3.6 without any bundle. Then right click ad "Run as Administrator" the batch file named:
install-required-modules-windows-run-as-administrator.bat

to install the required packages.

See also the wiki: https://github.com/ProfHoekstra/bluesky/wiki/Installation<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfHoekstra%2Fbluesky%2Fwiki%2FInstallation&data=02%7C01%7Cyingxiao.kong%40vanderbilt.edu%7Ce7307d48085f47a9e1f808d59001d4fe%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636573259899296670&sdata=2Ul74yeoo1xnKYDKOqm8HiE0GjG90QW32iw%2FqYtt3XA%3D&reserved=0>

Best regards,
Jacco Hoekstra

**Comment by YingxiaoKong** [comment]
Hi Joost,

I tried the newest version and it works! Thank you for telling me that!

On Mar 22, 2018, at 9:33 AM, ProfHoekstra <notifications@github.com<mailto:notifications@github.com>> wrote:


You're not running the latest version. Instead of installing a release, simply click the green button "Download as zip" and you have the latest version.

Then install Python 3.6 without any bundle. Then right click ad "Run as Administrator" the batch file named:
install-required-modules-windows-run-as-administrator.bat

to install the required packages.

See also the wiki: https://github.com/ProfHoekstra/bluesky/wiki/Installation<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FProfHoekstra%2Fbluesky%2Fwiki%2FInstallation&data=02%7C01%7Cyingxiao.kong%40vanderbilt.edu%7Ce7307d48085f47a9e1f808d59001d4fe%7Cba5a7f39e3be4ab3b45067fa80faecad%7C0%7C0%7C636573259899296670&sdata=2Ul74yeoo1xnKYDKOqm8HiE0GjG90QW32iw%2FqYtt3XA%3D&reserved=0>

Best regards,
Jacco Hoekstra

**Comment by jooste** [comment]
Good to hear!
