### ISSUE TITLE
Prediction of the ground's planes's movements by using machine learning

### ISSUE THREAD

**Issue by Pyjamask** [ProfHoekstra/bluesky#150]
Hi !
I found bluesky on the Internet during my researches. By installing the application I was fooled by the remarkable work supplied by all the community
Today I work on a subject on the prediction of the ground's planes's movements by using machine learning, the genetic algorithms, network neuron ...
Now I'd like to know if bluesky could allow me to add my airport map which I want to make my simulations. And I would like to know which environment of development I need to use it as well as possible.
I'd like to know how is made the management of the ground's movements or the prediction for example for the scenario " EHAM-TAXI.SCN 

Thank you for you help

Best regards

Yassine Dabachine

**Comment by jooste** [comment]
For the visualization of airport maps, BlueSky uses a database from x-plane. If your airport is not in this database you can use the [X-plane world editor](https://developer.x-plane.com/tools/worldeditor/) to create it.

**Comment by ProfHoekstra** [comment]
Dear Yassine,

Regarding your two questions:
ADD YOUR OWN AIRPORT
If you zoom in and your airport is not on the map, then you could add your own virtual airport map to the screen:
- make a text file draw-apt.scn.
- then you can simply add any features to the screen using the commands after the time stamp of zero, for example (see wiki for description of commands), names can be arbitrary are simply used to delete, always start with an alphabetical character.:

00:00:00.00>BOX name,lat1,lon1,lat2,lon2
00:00:00.00>CIRCLE name,lat,lon,radius
00:00:00.00>LINE name,lat0,lon0,lat1,lon1
Also your can give the airport a name by defining a waypoint with DEFWPT (see also below)

MAKE A TAXI SCENARIO
The logic of taxi routes is the same as when in–flight. Zoom in to your airport, use DEFWPT name, and click the lat/lon position. If you switch on SAVEIC taxiwpts.scn before this, then all your command will be saved in taxirte1.scn.

Then you can make separate scenario file with different taxi-route:
For instance in taxiroute1:
00:00:00.00>%0 ADDWPT TAXIWPA1
00:00:00.00>%0 ADDWPT TAXIWPA2
00:00:00.00>%0 ADDWPT TAXIWPB1
00:00:00.00>%0 ADDWPT TAXIWPB3

The from your main scenario file, your first call the drawapt.scn, then the taxi waypoints and then the route for different aircraft:
00:00:00.00>CALL drawapt.scn
00:00:00.00>CALL taxiwpts.scn
00:00:00.00>CALL taxiroute1 KL204
00:00:00.00>CALL taxiroute1 MP205

This gives aircraft KL204 the route specified in taxiroute.1scn, then MP205 gets the same route.

In this way you can make different routes. Use LNAV ON to make it steer and VNAV OFF to have control over the speed yourself. With “KL204 DIRECT TAXIWPA2” you control the active waypoint to go to first. Then shifting of waypoints should happen automatically, including turns.

You can also skip the phase of defining waypoints and directly click in the route with SAVEIC as ADDPWT also accepts lat,lon waypoints. But this means using DIRECT becomes harder as each waypoint gets a long, unique name.

Hope this helps, good luck. Taxi scenarios are often a lot of work due to the many turns.

Best regards,
      Jacco Hoekstra

**Comment by Pyjamask** [comment]
Hi

Thank you for answering me  

I'm programming an algorithm of prediction by using Machine Learning.

The problem I have is that to make the learning for my algorithm I need an extract of real data such as 
landings---> taxiway---> parking lot (movement on the ground in case of landing) 
weather report---> landing 

I have examine on open data without result whatever is the airport.

Thank you for your help

Best regards

Yassine Dabachine

**Comment by ProfHoekstra** [comment]
Maybe check out navdb module?

Best regards/Met vriendelijke groeten,
    Jacco Hoekstra


On 12 Apr 2018, at 22:42, Pyjamask <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi

Thank you for answering me

I'm programming an algorithm of prediction by using Machine Learning.

The problem I have is that to make the learning for my algorithm I need an extract of real data such as
landings---> taxiway---> parking lot (movement on the ground in case of landing)
weather report---> landing

I have examine on open data without result whatever is the airport.

Thank you for your help

Best regards

Yassine Dabachine

**Comment by Pyjamask** [comment]
Hi,

please can you send me a link to find navdb module ?

Best regards
Yassine Dabachine
