### ISSUE TITLE
Problem executing bluesky for the first time

### ISSUE THREAD

**Issue by Gabotero** [ProfHoekstra/bluesky#160]
Hi, I've installed all the requirements and checked with "check.py". However, when I execute Bluesky.py this is the only thing that comes out, no windows at all:

> Reading config from settings.cfg
   *****   BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Using Python-based geo functions
Loading global navigation database...
Reading cache: data/cache/py3/navdata.p
Accepting event connections on port 9000, and stream connections on port 9001
Discovery is disabled
Reading config from settings.cfg
Loading palette bluesky-default
Bluesky needs None
Install using e.g. pip install None
BlueSky normal end.
Using Python-based geo functions
Loading global navigation database...
Reading cache: data/cache/py3/navdata.p
StateBasedCD: using default Python version, no compiled version for this platform.
StateBasedCD: using Python version.
Using BlueSky performance model
Successfully loaded plugin AREA
Successfully loaded plugin DATAFEED
Node started, id=b'\x00cb\x00\xf7'

Same behaviour for "Bluesky_qtgl.py". Nevertheless, "Bluesky_pygame.py" shows a loading screen with a plane logo, then loads a bigger black screen and finally it crashes with the following exception:
 
> Reading coastlines.dat
     230912  coastlines added.
Traceback (most recent call last):
  File "BlueSky_pygame.py", line 36, in <module>
    main()
  File "BlueSky_pygame.py", line 19, in main
    bs.scr.update()   # GUI update
  File "/home/user/Desktop/bluesky-master/bluesky/ui/pygame/screen.py", line 745, in update
    if bs.traf.asas.nconf>0:
AttributeError: 'ASAS' object has no attribute 'nconf'

My system is Ubuntu 16.04 with python3 installed. Also I had to downgrade pyqt5 version from 5.11.2 to 5.10.1 so that it doesn't crash with "undefined symbol: PySlice_AdjustIndices" exception.
I was just curious about this software and decided to give it a try. If this is not my fault, I hope this helps to solve any future bugs.
Thanks.

**Comment by ProfHoekstra** [comment]
Pygame crash will be solved in coming days.

The qtgl-problem might have to do with the ports used to communicate between GUI and sim. Joost, do you recognize this?

Kind regards,
    Jacco Hoekstra


On 13 Jul 2018, at 18:17, Gabriel <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, I've installed all the requirements and checked with "check.py". However, when I execute Bluesky.py this is the only thing that comes out, no windows at all:

Reading config from settings.cfg
***** BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Using Python-based geo functions
Loading global navigation database...
Reading cache: data/cache/py3/navdata.p
Accepting event connections on port 9000, and stream connections on port 9001
Discovery is disabled
Reading config from settings.cfg
Loading palette bluesky-default
Bluesky needs None
Install using e.g. pip install None
BlueSky normal end.
Using Python-based geo functions
Loading global navigation database...
Reading cache: data/cache/py3/navdata.p
StateBasedCD: using default Python version, no compiled version for this platform.
StateBasedCD: using Python version.
Using BlueSky performance model
Successfully loaded plugin AREA
Successfully loaded plugin DATAFEED
Node started, id=b'\x00cb\x00\xf7'

Same behaviour for "Bluesky_qtgl.py". Nevertheless, "Bluesky_pygame.py" shows a loading screen with a plane logo, then loads a bigger black screen and finally it crashes with the following exception:

Reading coastlines.dat
230912 coastlines added.
Traceback (most recent call last):
File "BlueSky_pygame.py", line 36, in
main()
File "BlueSky_pygame.py", line 19, in main
bs.scr.update() # GUI update
File "/home/user/Desktop/bluesky-master/bluesky/ui/pygame/screen.py", line 745, in update
if bs.traf.asas.nconf>0:
AttributeError: 'ASAS' object has no attribute 'nconf'

My system is Ubuntu 16.04 with python3 installed. Also I had to downgrade pyqt5 version from 5.11.2 to 5.10.1 so that it doesn't crash with "undefined symbol: PySlice_AdjustIndices" exception.
I was just curious about this software and decided to give it a try. If this is not my fault, I hope this helps to solve any future bugs.
Thanks.

**Comment by jooste** [comment]
It seems to be an import error that we don’t recognise, because of the 'Bluesky needs None 
Install using e.g. pip install None’.

**Comment by ProfHoekstra** [comment]
Pygame version fixed: ASAS interface updated to newest version of conflict detection output

Could you please try running the updated pygame version?

Best regards,
    Jacco Hoekstra

**Comment by Gabotero** [comment]
I've downloaded the updated code again and now it works.

What was the problem then?
Thank you very much for your time.

Regards,
Gabriel.

**Comment by ProfHoekstra** [comment]
The BlueSky Pygame GUI had to be adjusted after an ASAS update, which meant the variable names of the conflict data were changed slightly.

Met vriendelijke groeten,
    Jacco Hoekstra


On 16 Jul 2018, at 13:02, Gabriel <notifications@github.com<mailto:notifications@github.com>> wrote:


I've downloaded the updated code again and now it works.

What was the problem then?
Thank you very much for your time.

Regards,
Gabriel.

**Comment by klippehu** [comment]
Hi, I just met the same problem. When I start the qtgl version , there is not any error or warning, but nothing happened on my screen either. 

The console shows me :

`   *****   BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Using Python-based geo functions
Loading global navigation database...
Reading cache: data/cache\py3\navdata.p
Accepting event connections on port 9000, and stream connections on port 9001
Discovery is disabled
Loading palette bluesky-default
Bluesky needs None
Install using e.g. pip install None
BlueSky normal end.
README.md
Reading config from settings.cfg
Using Python-based geo functions
Loading global navigation database...
Reading cache: data/cache\py3\navdata.p
StateBasedCD: using default Python version, no compiled version for this platform.
StateBasedCD: using Python version.
Using BlueSky performance model
Successfully loaded plugin AREA
Successfully loaded plugin DATAFEED
Node started, id=b'\x00\x99E\xd3\xb2'`

**Comment by jooste** [comment]
Hi @klippehu, could you try the following:

in BlueSky_qtgl.py:

in line 28: replace `try:` with `if True:`
and comment out lines 41-44.

The original exception should be printed to the console then. If you copy that in your reply maybe we can find out which package is missing.

**Comment by klippehu** [comment]
@jooste 
Thank you for your response.
After commenting 41-44 lines, got a error as following:
ImportError: cannot import name 'Collection'
The class Collection in collections.abc was imported in python3.6, but my python interpreter is 3.5.
Do I have to change to 3.6?

**Comment by jooste** [comment]
This would be the easiest solution. 
In python 3.5 I think You should remove the .abc' from the import statement. This was changed in 3.6.

**Comment by jooste** [comment]
The problem with collections.abc is fixed in commit d346820.
