### ISSUE TITLE
OpenGL Ubuntu 16 with Anaconda

### ISSUE THREAD

**Issue by marcbrittain** [ProfHoekstra/bluesky#166]
Hi Joost and Jacco,

I was working in Ubuntu 16 with two Nvidia graphics cards: 1080 Ti and Titan Xp. As both of these cards support OpenGL I was still getting many issues when trying to run the OpenGl version of BlueSky. Other important information is that I am using python 3.6 within an anaconda environment. 

My first error was that the 'xcb' plugin for OpenGl could not be found. I was able to fix this by creating a variable from the command line:

```python
export QT_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/
```
After rebooting the command line, the first issue was solved but when running the check.py file I still was unable to use the OpenGl capabilities. I solved this problem by updating my base conda distribution and updating all of the packages. Here is the link to the commands I used for reference (only used first 2):

http://docs.glueviz.org/en/stable/known_issues.html#d-viewers-not-working-on-linux-with-pyqt5

I figured it would be beneficial to share what I ran into and how to solve it! Now everything is working great!

-Marc

**Comment by jooste** [comment]
Hi Marc,

Thanks for the tip, this is something we can add to the installation instructions on the bluesky wiki.
On a sidenote: I think that on linux, you're better off using the native package manager of your distribution to install python and other libraries, instead of a bundle like anaconda. Some distributions may even install python by default.

**Comment by jooste** [comment]
I updated the installation instructions on the BlueSky wiki following your suggestions. Thanks again!
