### ISSUE TITLE
Ducumentation via wiki

### ISSUE THREAD

**Issue by espinielli** [ProfHoekstra/bluesky#75]
I would suggest to integrate the documentation via the wiki (using Markdown).
One memorable example is [d3.js](https://github.com/d3/d3/wiki), but it does not have to be so complicated.

Few advantages come to mind:
1. possibility to get contributions (not everybody uses MS Word or likes it)
1. better version control
1. browsable
1. you can still turn the pages in PDF

**Comment by jooste** [comment]
The d3.js wiki indeed looks very good!

**Comment by jooste** [comment]
Since you opened this issue, a large amount of documentation has been added to the BlueSky wiki on github. In terms of usage, documentation on the TrafScript functions (with which you control bluesky from scenarios, the command line, and the network) is as good as complete. API documentation is also coming along, with the latest addition of a plugin system for BlueSky making it a lot easier to add functionality. Together, I think, enough to close this issue. Thanks again for your suggestions!
