### ISSUE TITLE
指令TRAIL会导致程序崩溃

### ISSUE THREAD

**Issue by avalonyzhily** [ProfHoekstra/bluesky#80]
pygame模式下启动项目，然后开始仿真之后，
如果输入TRAIL指令参数为ON的时候，程序会崩溃。
错误点在screen模块下，提示traf.lastlat中Traffic中没有lastlat属性。

**Comment by ProfHoekstra** [comment]
Ok, I will test TRAIL ON in the pygame version and fix any potential issues with traffic.lastlat. Bugs in this might also be due to the fact that TRAILS is not (yet) available in the Qt version and hence not used a lot at this moment.

Met vriendelijke groeten,
    Jacco Hoekstra


On 2 Mar 2017, at 05:45, avalonyzhily <notifications@github.com<mailto:notifications@github.com>> wrote:


pygame模式下启动项目，然后开始仿真之后，
如果输入TRAIL指令参数为ON的时候，程序会崩溃。
错误点在screen模块下，提示traf.lastlat中Traffic中没有lastlat属性。

―

**Comment by avalonyzhily** [comment]
Thank you for your reply!
There is some unknow reason make my machine can't run project in QT version.
So,I only can use the pygame version to research code...
And there are many places which don't understand about this project,
would you provide more details docs about Traffic And Metric ?
That would be great！

Thanks again~

with kind regards
 He Miaolin 
 
ps:I just use Chinese because my English is not very good,so sorry.....

**Comment by jooste** [comment]
Hi avalonyzhily, what happens when you run the Qt version? can you copy the console output? Also relevant are the specs of your computer, especially your graphics card.

**Comment by avalonyzhily** [comment]
I'm so sorry that I can use the QT version on my personal computer.
So,I think that  is the problem of my work computer.
