### ISSUE TITLE
TCP connection to simulation is one-way only

### ISSUE THREAD

**Issue by jacobythwaites** [ProfHoekstra/bluesky#94]
If I start an opengl simulation using `python BlueSky.py`, it listens on port `8888` for incoming console connections.

I connect using netcat and issue a command, as follows:
```
% nc 127.0.0.1 8888
airport egkk
```
Both the command (as issued in lower case) and the output result of the command appear on the gui console.

I would expect the output of the command to appear on the TCP connection, and the GUI console to remain unchanged.

**Comment by jooste** [comment]
Hi,
This is indeed the case. The telnet connection hasn't been developed beyond a very simple implementation yet. Ideally it would work the way you describe, but this requires more than a simple fix. Because stack commands can originate from several different places, where some need their feedback to be sent everywhere, and others the other way around, implementing this correctly would require a formalised way of tracking source and destination of stack I/O.

We also have the wish to change from the several different network libraries that we use now (python socket, QT network, multiproccessing.Connection) to just one library (zmq), which will also make it easier to provide TCP/UDP output streams (e.g., to drive HITL simulations). When we get around to this the stack command origin/destination issue will also be addressed.

**Comment by reube** [comment]
Hi @jooste I have implemented a relatively simple fix for this on a fork (which we are keeping up-to-date with this upstream repo).  I'll tidy and submit a pull request in the next few days - just writing some tests currently.  It may represent a useful fix for the time being.

**Comment by reube** [comment]
Please see https://github.com/ProfHoekstra/bluesky/pull/103
@jooste @ProfHoekstra
